export enum ModelNames {
  Areas = 'Areas',
  BranchInventory = 'BranchInventory',
  Branches = 'Branches',
  Organizations = 'Organizations',
  Products = 'Products',
  Users = 'Users',
  AdminUser = "AdminUser",
  Whatsappsettings = 'Whatsappsettings',
  Zones = 'Zones',
  SubscriptionPlans = 'SubscriptionPlans',
  Subscriptions = 'Subscriptions',
  CreditBalance = 'CreditsBalance',
  CreditTransactions = 'CreditTransactions',
  UsageRecords = 'UsageRecords',
  ProductOptions = 'ProductOptions',
  ProductOptionChoices = 'ProductOptionChoices',
  Notifications = 'Notifications',
  Request = "Request"
}
